[package]
name = "influx-client"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
influx-contracts = { git = "https://github.com/ijagberg/influx-contracts.git", branch = "main" }
reqwest = "0.10.8"

[dev-dependencies]
tokio = { version = "0.2.22", features = ["full"] }
