[package]
name = "influx"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10.8"
csv = "1.1.3"
pretty_env_logger = "0.4.0"
log = "0.4.8"
chrono = "0.4.19"

[dev-dependencies]
tokio = { version = "0.2.22", features = ["full"] }
serde = { version = "1.0.116", features = ["derive"] }
