[package]
name = "influx"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10.8"

[dev-dependencies]
tokio = { version = "0.2.22", features = ["full"] }
