[package]
name = "influx"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.11.2"
log = "0.4.8"
chrono = "0.4.19"

[dev-dependencies]
tokio = { version = "1.3.0", features = ["full"] }
serde = { version = "1.0.116", features = ["derive"] }
dotenv = "0.15.0"
pretty_env_logger = "0.4.0"
